### ISSUE TITLE
Flash demo not working, even with Ruffle

### ISSUE THREAD

**Issue by torokati44** [sparkbox/bouncy-ball#117]
The Flash demo is hard-coded to be unsupported, even though, with [Ruffle](https://ruffle.rs), it works.

I recommend something similar to this method: https://stackoverflow.com/a/42815720/635587
In place of this: https://github.com/sparkbox/bouncy-ball/blob/7f2f5ca70d5f7eaf2003e219a3ef9c6d21fc5dae/site/js/updatePanes.js#L89-L92

**Comment by danielhjacobs** [comment]
I suggest switching `return false` to `return !!navigator.plugins.namedItem("Shockwave Flash")`. This is also useful for browsers that can still support Flash, like Pale Moon or Basilisk.

**Comment by bryanbraun** [comment]
Great idea. I tested this with Ruffle and it works. 🙌

<img width="888" alt="Screenshot 2024-02-03 at 6 43 05 AM" src="https://github.com/sparkbox/bouncy-ball/assets/1256329/56dcd63b-5c5f-4077-9cd6-37fd6351bd86">

Pushing this up now.

**Comment by torokati44** [comment]
It's a bit cut off on the right, not sure if that's Ruffle's fault, or the SWF is just like that. Would have to check in Flash Player to be sure.
