### ISSUE TITLE
Change the docs toggle from a link to button

### ISSUE THREAD

**Issue by bryanbraun** [sparkbox/bouncy-ball#14]
Currently, the toggle for open/closing the docs about each animation uses an `<a>` element:

![bouncy_ball_-_compare_web_animation_techniques](https://cloud.githubusercontent.com/assets/1256329/18958127/9cf0700a-862f-11e6-96db-d79b598a0482.png)

This works but it would probably be more meaningful and accessible to use a `<button>` element styled as a link instead. [Several](https://css-tricks.com/use-button-element/#article-header-id-2) [posts](http://www.karlgroves.com/2013/05/14/links-are-not-buttons-neither-are-divs-and-spans/) recommend this.

The change would include:
- Replacing the `<a>` element with a `<button>` element.
- Override the default styles for the button to make it look like it a link. The idea is for it to stylistically look the same as it currently does.
- Check that there are no functional regressions.

**Comment by lavish205** [comment]
Hi @bryanbraun 
I would love to work on this bug.

**Comment by bryanbraun** [comment]
@lavish205, awesome! I added some [more detailed development/contribution workflow instructions](https://github.com/sparkbox/bouncy-ball/blob/gh-pages/contributing.md#development-workflow), if that helps. Let me know if you have any questions.

**Comment by lavish205** [comment]
Thanks @bryanbraun that was much required

**Comment by amitsin6h** [comment]
@bryanbraun you can close this issue. I have added the button and also changed the text color as it was not visible with button and now it really looks cool!! :)
