### ISSUE TITLE
Add a local development server

### ISSUE THREAD

**Issue by bryanbraun** [sparkbox/bouncy-ball#15]
Currently, there's nothing included with the project to serve the static files during local development. [We currently recommend using something like python's SimpleHTTPServer](https://github.com/sparkbox/bouncy-ball/blob/gh-pages/contributing.md#development-workflow), but that won't work for people who don't have it pre-installed on their machine.

We should:
  1. Include a local server (like https://www.npmjs.com/package/http-server) in the npm `package.json` file.
  2. Set up an [npm scripts](https://docs.npmjs.com/misc/scripts) task (like `npm run server`?) that kicks off the server
  3. Update [the instructions in contributing.md](https://github.com/sparkbox/bouncy-ball/blob/gh-pages/contributing.md#development-workflow) to use the new local server.

Any other suggestions for making local development easier

**Comment by jrasanen** [comment]
Hi, I could look into this one. :)

**Comment by bryanbraun** [comment]
Awesome! Thanks @jrasanen!

**Comment by jrasanen** [comment]
@bryanbraun opened a PR

**Comment by bryanbraun** [comment]
The fix was merged in https://github.com/sparkbox/bouncy-ball/pull/16. Thanks again @jrasanen.

![](https://media3.giphy.com/media/8vAD2l1DohNL2/200.gif)
