### ISSUE TITLE
Add a Bouncy-Ball Demo using D3

### ISSUE THREAD

**Issue by bryanbraun** [sparkbox/bouncy-ball#21]
Add a [bouncy-ball demo](http://sparkbox.github.io/bouncy-ball/) using D3.

This would be a good contribution for somebody familiar with [D3](https://d3js.org/) and its ecosystem. 

I _think_ the right supporting library to use would be [d3-transition](https://github.com/d3/d3-transition), but I'm not as familiar with that ecosystem, so hopefully you can confirm that via research or experience.

A few tips for making this:
  1. Start by duplicating the `/examples/template` folder and renaming your copy to something like `d3`, and create the animation in `/examples/d3/index.html`
  2. Look at the other demos for reference parameters. For example, you can find details on ball-size, bounce height, easings, cubic-bezier functions, and more.
  3. To bring it into the main page, just add [a new `<input>` and `<label>` for it in the selection bar](https://github.com/sparkbox/bouncy-ball/blob/e2776c5ed02b152a040d1406fedc05cbe264b289/index.html#L41-L42).

**Comment by bryanbraun** [comment]
(update: there's a PR up to address this at https://github.com/sparkbox/bouncy-ball/pull/23)

**Comment by AmGarera** [comment]
Going to be submitting my pull tonight, got this done pretty quick

**Comment by bryanbraun** [comment]
Fixed in #26. Closing.
