### ISSUE TITLE
Possible new animation methods

### ISSUE THREAD

**Issue by tigt** [sparkbox/bouncy-ball#35]
During the last presentation, I noted proposed animation methods, and added a few of my own:

* `<canvas>`
  - 2D context
  - 3D context (WebGL)

* `<video>` — just .mp4 is sufficient nowadays

* GIF, [animated WebP](https://developers.google.com/speed/webp/faq#why_should_i_use_animated_webp), [Animated PNG](https://en.wikipedia.org/wiki/APNG) — probably all 3 at once using `<picture>`:
  ```html
  <picture>
    <source srcset="ball.webp" type="image/apng">
    <source srcset="ball.apng" type="image/webp">
    <img src="ball.gif" alt="Bouncy ball">
  </picture>
   ```

* SVG in OpenType — [view in Firefox](https://people-mozilla.org/~jkew/opentype-svg/soccer.html)

* `<marquee>` (I can post my code; it's mostly the derivative of the pure-JS algorithm feeding into the `scrollamount` attribute)

* [`application/x-multi-part-mixed-replace`](https://web.archive.org/web/19981203153836/fishcam.netscape.com/assist/net_sites/pushpull.html) — this is how those ancient webcams worked; [remember those](https://sites.google.com/a/montulli.org/about-fishcam/Home/history)?

* Flash

* WebVR

* Cromwell once joked about making an HTC file for old IE

**Comment by bryanbraun** [comment]
@tigt, thanks for getting these down.

One constraint I'd like to keep is that "_Any new animation should work on the demo page and be visually indistinguishable from existing animations (except for the color of the ball)_" (that's in the [contribution guidelines](https://github.com/sparkbox/bouncy-ball/blob/master/contributing.md)).

I _think_ that eliminates a couple of these options (like WebVR and WebGL 3D context).

I'm going to go ahead and split the remaining ones out into separate issues, so they are easy to claim.

**Comment by bryanbraun** [comment]
Ok @tigt, I've created a bunch of separate issues for your suggestions (https://github.com/sparkbox/bouncy-ball/issues/42, https://github.com/sparkbox/bouncy-ball/issues/41, https://github.com/sparkbox/bouncy-ball/issues/40, https://github.com/sparkbox/bouncy-ball/issues/39, https://github.com/sparkbox/bouncy-ball/issues/38). I'm going to go ahead and close this one. Thanks again. 🙌

**Comment by tigt** [comment]
Glad it came in handy. WebGL 3D context can be made to look identical, though; it just enables the GPU's 3D processing instead of accelerated raster commands.

**Comment by bryanbraun** [comment]
Oh cool. I'm open to a WebGL example that looks identical.
