### ISSUE TITLE
Add an example using Flash

### ISSUE THREAD

**Issue by bryanbraun** [sparkbox/bouncy-ball#41]
Yes, I'm serious.

I don't know how to make a flash animation, so I'm relying on somebody else to contribute this one (@zastrow? 😅).

**Comment by zastrow** [comment]
Right. Right. I keep making half steps and forget. The last one was downloading <s>Flash</s> Animate. I’ll do it. I’m on it.

**Comment by zastrow** [comment]
Assign this issue to me even 😜
