### ISSUE TITLE
Add a WebGL example?

### ISSUE THREAD

**Issue by bryanbraun** [sparkbox/bouncy-ball#43]
This would mean using the WebGL 3DContext APIs to render a bouncing ball, without any 3rd party libraries.

I'm not sure what this code would end up looking like. I'm most interested in adding the demo if the code has non-trivial differences to other existing approaches (like canvas, for instance).

*Important:* this doesn't mean adding a 3D version. Any example using WebGL would need to visually look the same as the existing demos, as described in [the contribution guidelines](https://github.com/sparkbox/bouncy-ball/blob/master/contributing.md#contribute).

**Comment by subu28** [comment]
I will work on this. Give me upto 17 Oct

**Comment by subu28** [comment]
@bryanbraun hey did you check the pull request? Let me know if you want me to do any changes to it.

**Comment by bryanbraun** [comment]
@subu28, ah yes thanks for the reminder. I should be able to get to it this weekend. 👍
