### ISSUE TITLE
Minor GreenSock tweaks

### ISSUE THREAD

**Issue by jackdoyle** [sparkbox/bouncy-ball#47]
No need to create a variable to store the ball element - GSAP has a selector (document.querySelectorAll()) built in, so you could simplify it to: 
```javascript
TweenMax.to("ball", 0.575, {
  y: 160,
  repeat: -1,
  yoyo: true,
  ease: Power1.easeIn
});
```
Also, it's GreenSock, not Greensock (capital "S") :)

Thanks again for putting this whole thing together. Just watched the Fluent video of your presentation (https://www.youtube.com/watch?v=_TmhQI6X4JA) - nice job!

**Comment by bryanbraun** [comment]
@jackdoyle, thanks for the feedback. Great suggestions. 😄
