### ISSUE TITLE
Vanilla JS quadratic function easing

### ISSUE THREAD

**Issue by omasback** [sparkbox/bouncy-ball#5]
The Vanilla JS implementation uses kinematic equations, which is a good common sense way to simulate physics, but I thought I'd have a crack at a different approach just for fun. See my pen for an implementation that positions the ball using a quadratic function. 

http://codepen.io/omasback/pen/zBXLBX

It definitely took me a while to figure out the math for this, so it's not an technique I would recommend using for work unless the developer is already familiar with the math. But I think it could serve as good inspiration regardless. I'm not sure if this has a place here, maybe alongside the existing Vanilla JS version? maybe have two vanillas? Let me know if you'd like a pull request

**Comment by bryanbraun** [comment]
@omasback, this is fantastic! 😍 

I think it would be great to replace the VanillaJS one with this. A similar kinematic technique is used on P5, so people can still look at that demo, if they want to see that kind of approach it.

Plus, the physics-based approaches don't align with the other approaches very well.

The only downside is this is a bit trickier to understand the math, like you said. What if we added a comment to the source with a link to a visual position graph (like this one I put together: https://www.desmos.com/calculator/zivy8qxxca). That way people can see that this is a position function, and fiddle with the values if they want to understand it more.

(I adjusted the graphed function to account for translateY, so it looks more like a bounce path. Hopefully that won't lose people.)

Let me know what you think, and if you could put together a PR, that would be great.

**Comment by bryanbraun** [comment]
Hey @omasback, I had some time so I put in a PR that uses your approach. Feel free to take a look at the PR if you want... I'll plan to merge it in a bit if nobody has concerns.

**Comment by omasback** [comment]
Looks good man!

**Comment by Krupinov** [comment]
Hello!
My name is Ruslan.

Your code contains the formula : 
ypos = a * Math.pow(((time + h) % (h * 2) - h), 2) + k;

If I set negative values for the variable "time", I get negative values "ypos". But this is different from the graph you have in the comment: https://www.desmos.com/calculator/i6yunccp7v 
In this chart, the value on the Y axis remains positive at any value of "t" ( time ). 
Tell me, please, where is the error in your formula ?

**Comment by bryanbraun** [comment]
Hi Ruslan.

The function on Desmos uses the the `mod()` function while the javascript function uses the `%` operator (commonly called modulo). It looks like these two functions have different behaviors for negative numbers: https://stackoverflow.com/q/4467539/1154642

This doesn't affect bouncy-ball because our timestamps are always positive. The linked article above gives some ideas if you need JavaScript's `%` to behave more like `mod()`.

**Comment by Krupinov** [comment]
Hi Bryan!

Thank you so much for the answer. I'm sorry I took Your time. I completely forgot about Stackoverflow :)
Yes, it would be great if we could Unscrew the time Back :)
