### ISSUE TITLE
Update GreenSock demo to use the latest version of GreenSock

### ISSUE THREAD

**Issue by bryanbraun** [sparkbox/bouncy-ball#78]
We need to update the GreenSock demo to use the latest version of GreenSock. Steps include:

- Download the latest version of the library, and place it in the `examples/[library-name]` folder. Minified files preferred, but non-minified works.
    - The filename should include the version number in it (for example: `jquery-3.0.0.min.js`).
- Update the demo to use the updated library, including any necessary code changes to the demo.
- Verify that the demo works across a sample of modern browsers (like Firefox, Chrome, Safari, and Edge).
    - [Follow the instructions here](https://github.com/sparkbox/bouncy-ball/blob/master/contributing.md#development-workflow) to run a test version of the site locally.
- Commit your changes and submit a pull request.

**Comment by ishanarya0** [comment]
Hi @bryanbraun , may I work on it when hacktober starts?

**Comment by bryanbraun** [comment]
@ishanarya0, sure thing. I'll assign it to you. 👍

**Comment by bryanbraun** [comment]
Merged in https://github.com/sparkbox/bouncy-ball/pull/100. Thanks for contributing. 🏆
