### ISSUE TITLE
Update Velocity demo to use the latest version of Velocity

### ISSUE THREAD

**Issue by bryanbraun** [sparkbox/bouncy-ball#80]
We need to update the Velocity demo to use the latest version of Velocity. Steps include:

- Download the latest version of the library, and place it in the `examples/[library-name]` folder. Minified files preferred, but non-minified works.
    - The filename should include the version number in it (for example: `jquery-3.0.0.min.js`).
- Update the demo to use the updated library, including any necessary code changes to the demo.
- Verify that the demo works across a sample of modern browsers (like Firefox, Chrome, Safari, and Edge).
    - [Follow the instructions here](https://github.com/sparkbox/bouncy-ball/blob/master/contributing.md#development-workflow) to run a test version of the site locally.
- Commit your changes and submit a pull request.

**Comment by devcshort** [comment]
Would I be able to work on this once hacktoberfest starts?

**Comment by bryanbraun** [comment]
Sure! Assigning it to you now. 👍

**Comment by devcshort** [comment]
Just submitted a PR #98

**Comment by bryanbraun** [comment]
Merged! Thanks for contributing. 🏆
