### ISSUE TITLE
Update Anime demo to use the latest version of Anime

### ISSUE THREAD

**Issue by bryanbraun** [sparkbox/bouncy-ball#82]
We need to update the Anime.js demo to use the latest version of Anime.js. Steps include:

- Download the latest version of the library, and place it in the `examples/[library-name]` folder. Minified files preferred, but non-minified works.
    - The filename should include the version number in it (for example: `jquery-3.0.0.min.js`).
- Update the demo to use the updated library, including any necessary code changes to the demo.
- Verify that the demo works across a sample of modern browsers (like Firefox, Chrome, Safari, and Edge).
    - [Follow the instructions here](https://github.com/sparkbox/bouncy-ball/blob/master/contributing.md#development-workflow) to run a test version of the site locally.
- Commit your changes and submit a pull request.

**Comment by devcshort** [comment]
Can I work on this once hacktoberfest officially starts?

**Comment by bryanbraun** [comment]
Yep! Assigning it to you now. 👍

**Comment by devcshort** [comment]
Created a PR #99

**Comment by bryanbraun** [comment]
Merged! 🏆 🏆 🏆 🏆 🏆 🏆
