### ISSUE TITLE
Update D3 demo to use the latest version of D3

### ISSUE THREAD

**Issue by bryanbraun** [sparkbox/bouncy-ball#83]
We need to update the D3 demo to use the latest version of D3. Steps include:

- Download the latest version of the library, and place it in the `examples/[library-name]` folder. Minified files preferred, but non-minified works.
    - The filename should include the version number in it (for example: `jquery-3.0.0.min.js`).
- Update the demo to use the updated library, including any necessary code changes to the demo.
- Verify that the demo works across a sample of modern browsers (like Firefox, Chrome, Safari, and Edge).
    - [Follow the instructions here](https://github.com/sparkbox/bouncy-ball/blob/master/contributing.md#development-workflow) to run a test version of the site locally.
- Commit your changes and submit a pull request.

**Comment by Apoorve73** [comment]
I haven't worked on D3.js but would like to learn and solve this issue.

**Comment by bryanbraun** [comment]
Hey @Apoorve73, sorry, I didn't notice your comment until after merging this PR. 😞 

There are [several other issues open](https://github.com/sparkbox/bouncy-ball/issues) that were similar to this one... feel free to look into one of those, if you'd like.

**Comment by capellini** [comment]
@Apoorve73 I'm sorry, as well.  I didn't mean to step on your toes and didn't notice that you asked to work on this until after I had submitted my PR.

**Comment by Apoorve73** [comment]
No worries! I will try to work on other issues in your repo! 
Thanks a lot for taking the pain for writing this note :)
