### ISSUE TITLE
Update Lottie demo to use the latest version of Bodymovin

### ISSUE THREAD

**Issue by bryanbraun** [sparkbox/bouncy-ball#84]
We need to update the Lottie demo to use the latest version of Bodymovin. Steps include:

- Download the latest version of the library, and place it in the `examples/[library-name]` folder. Minified files are preferred, but non-minified works.
    - The filename should include the version number in it (for example: `jquery-3.0.0.min.js`).
- Update the demo to use the updated library, including any necessary code changes to the demo.
- Verify that the demo works across a sample of modern browsers (like Firefox, Chrome, Safari, and Edge).
    - [Follow the instructions here](https://github.com/sparkbox/bouncy-ball/blob/master/contributing.md#development-workflow) to run a test version of the site locally.
- Commit your changes and submit a pull request.

**Comment by SoldierCorp** [comment]
Hi,

I would like to help, can you assign it to me please?

**Comment by bryanbraun** [comment]
Sure thing! It's assigned. 👍

**Comment by SoldierCorp** [comment]
Hi @bryanbraun!

I finished the task but I am going to upload the PR on October 1st so this can count for Hacktoberfest, is that ok for you?

**Comment by bryanbraun** [comment]
@SoldierCorp, sure that works for me. 😄

**Comment by SoldierCorp** [comment]
Hi @bryanbraun  

Before I submit my PR, could you please read the Update for the event please https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by bryanbraun** [comment]
Hey @SoldierCorp, thanks for the heads-up. I've gone ahead and tagged this repo so it should be "opted-in" now. 👍
