### ISSUE TITLE
Update Mo.js demo to use the latest version of Mo.js

### ISSUE THREAD

**Issue by bryanbraun** [sparkbox/bouncy-ball#85]
We need to update the Mo.js demo to use the latest version of Mo.js. Steps include:

- Download the latest version of the library, and place it in the `examples/[library-name]` folder. Minified files preferred, but non-minified works.
    - The filename should include the version number in it (for example: `jquery-3.0.0.min.js`).
- Update the demo to use the updated library, including any necessary code changes to the demo.
- Verify that the demo works across a sample of modern browsers (like Firefox, Chrome, Safari, and Edge).
    - [Follow the instructions here](https://github.com/sparkbox/bouncy-ball/blob/master/contributing.md#development-workflow) to run a test version of the site locally.
- Commit your changes and submit a pull request.

**Comment by SamC302** [comment]
Can I work on this?

**Comment by bryanbraun** [comment]
@SamC302, yep, be my guest! 😄

**Comment by bryanbraun** [comment]
Fixed in https://github.com/sparkbox/bouncy-ball/pull/95. Thanks for the help! 👍
