### ISSUE TITLE
Update Matter.js demo to use the latest version of Matter.js

### ISSUE THREAD

**Issue by bryanbraun** [sparkbox/bouncy-ball#86]
We need to update the Matter.js demo to use the latest version of Matter.js . Steps include:

- Download the latest version of the library, and place it in the `examples/[library-name]` folder. Minified files preferred, but non-minified works.
    - The filename should include the version number in it (for example: `jquery-3.0.0.min.js`).
- Update the demo to use the updated library, including any necessary code changes to the demo.
- Verify that the demo works across a sample of modern browsers (like Firefox, Chrome, Safari, and Edge).
    - [Follow the instructions here](https://github.com/sparkbox/bouncy-ball/blob/master/contributing.md#development-workflow) to run a test version of the site locally.
- Commit your changes and submit a pull request.

**Comment by ishanarya0** [comment]
HI @bryanbraun , the current code is working with CDN, so an update to the CDN is required or a downloaded version of the library?

**Comment by bryanbraun** [comment]
@ishanarya0, I'd like to move away from using CDN links for this, so yes, it should use a downloaded version of the library. 👍

**Comment by bryanbraun** [comment]
Merged in https://github.com/sparkbox/bouncy-ball/pull/90. Thanks for the help!
