### ISSUE TITLE
Improve color contrast on some of the buttons

### ISSUE THREAD

**Issue by bryanbraun** [sparkbox/bouncy-ball#97]
Some of the buttons have poor color contrast, which is bad for accessibility. We should:

* Change any button colors that don't meet WCAG AA contrast requirements.
* Update the corresponding ball color to match.
    * Note: some of the ball colors might be difficult to change (like the ones for flash and video). If any of these need changing but would take special effort then feel free to create a separate issue for them.

**Comment by iAmNathanJ** [comment]
Working on it. Thanks!

**Comment by bryanbraun** [comment]
Merged this in https://github.com/sparkbox/bouncy-ball/pull/103. Thanks for the help @iAmNathanJ!
